"""create pdfs table

Revision ID: b0229d3bf199
Revises: 30a84d438097
Create Date: 2025-11-15 12:29:30.221003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0229d3bf199'
down_revision: Union[str, None] = '30a84d438097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pdfs', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pdfs', 'file',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pdfs', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_pdfs_id'), 'pdfs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdfs_id'), table_name='pdfs')
    op.alter_column('pdfs', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pdfs', 'file',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pdfs', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pdfs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
